# Generated by Django 5.2.8 on 2025-11-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
