# Generated by Django 5.2.8 on 2025-11-18 13:03

import market.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=15, null=True, unique=True, validators=[market.validators.validate_no_special_characters]),
        ),
    ]
