# Generated by Django 5.2.8 on 2025-11-19 14:54

import django.core.validators
import django.db.models.deletion
import market.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_user_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=60)),
                ('item_price', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('item_condition', models.CharField(choices=[('new', 'NEW'), ('excellent', 'EXCELLENT'), ('good', 'GOOD'), ('fair', 'FAIR'), ('poor', 'POOR')], default='good', max_length=10)),
                ('item_detail', models.TextField(blank=True, null=True)),
                ('item_image1', models.ImageField(upload_to=market.models.item_image_upload_to)),
                ('item_image2', models.ImageField(blank=True, null=True, upload_to=market.models.item_image_upload_to)),
                ('item_image3', models.ImageField(blank=True, null=True, upload_to=market.models.item_image_upload_to)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
                ('item_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
