# Generated by Django 5.2.8 on 2025-11-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_postitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
