# Generated by Django 5.2.8 on 2025-11-20 11:33

import django.core.validators
import market.models
import market.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='item_image1',
            field=models.ImageField(error_messages={'invalid_image': 'Please upload a valid image. This file is either not an image or is corrupted.'}, upload_to=market.models.item_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), market.validators.validate_image_mime_type]),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='item_image2',
            field=models.ImageField(blank=True, error_messages={'invalid_image': 'Please upload a valid image. This file is either not an image or is corrupted.'}, null=True, upload_to=market.models.item_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), market.validators.validate_image_mime_type]),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='item_image3',
            field=models.ImageField(blank=True, error_messages={'invalid_image': 'Please upload a valid image. This file is either not an image or is corrupted.'}, null=True, upload_to=market.models.item_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), market.validators.validate_image_mime_type]),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='item_price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Price must be at least 1 €.')]),
        ),
    ]
