# Generated by Django 5.2.8 on 2025-11-20 19:16

import django.core.validators
import market.models
import market.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_postitem_item_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='item_condition',
            field=models.CharField(choices=[('new', 'NEW'), ('excellent', 'EXCELLENT'), ('good', 'GOOD'), ('fair', 'FAIR'), ('poor', 'POOR')], default=None, error_messages={'blank': 'Please select a condition for your item.', 'invalid_choice': 'Invalid condition selected.'}, max_length=10),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='item_detail',
            field=models.TextField(default='No description provided', error_messages={'blank': 'Please enter a description for your item.', 'invalid': 'Please enter a valid description.'}),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='item_image1',
            field=models.ImageField(error_messages={'blank': 'Please upload a main image for your item.', 'invalid': 'Please upload a valid image file.', 'invalid_image': 'Please upload a valid JPEG or PNG image.'}, upload_to=market.models.item_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Please upload a JPEG or PNG image.'), market.validators.validate_image_mime_type]),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='item_image2',
            field=models.ImageField(blank=True, error_messages={'invalid': 'Please upload a valid image file.', 'invalid_image': 'Please upload a valid JPEG or PNG image.'}, null=True, upload_to=market.models.item_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Please upload a JPEG or PNG image.'), market.validators.validate_image_mime_type]),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='item_image3',
            field=models.ImageField(blank=True, error_messages={'invalid': 'Please upload a valid image file.', 'invalid_image': 'Please upload a valid JPEG or PNG image.'}, null=True, upload_to=market.models.item_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Please upload a JPEG or PNG image.'), market.validators.validate_image_mime_type]),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='item_price',
            field=models.PositiveIntegerField(error_messages={'blank': 'Please enter a price for your item.', 'invalid': 'Please enter a valid number.', 'min_value': 'Price must be at least 1 €.'}, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='item_title',
            field=models.CharField(error_messages={'blank': 'Please enter a title for your item.', 'invalid': 'Please enter a valid title.', 'max_length': 'Title is too long.'}, max_length=60),
        ),
    ]
