# Generated by Django 5.2.8 on 2025-11-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_postitem_item_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='item_detail',
            field=models.TextField(error_messages={'blank': 'Please enter a description for your item.', 'invalid': 'Please enter a valid description.'}),
        ),
    ]
