# Generated by Django 5.2.8 on 2025-11-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_alter_postitem_item_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
