# Generated by Django 5.2.8 on 2025-11-21 18:35

import market.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_postitem_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to=market.utils.profile_image_upload_to),
        ),
    ]
