# Generated by Django 5.2.8 on 2025-11-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_user_intro_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=5),
        ),
    ]
