# Generated by Django 5.2.8 on 2025-11-23 19:21

import market.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_user_seller_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=market.utils.profile_image_upload_to),
        ),
    ]
