# Generated by Django 5.2.8 on 2025-11-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('market', '0016_alter_like_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-dt_created']},
        ),
        migrations.AlterModelOptions(
            name='postitem',
            options={'ordering': ['-dt_created']},
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('author', 'content_type', 'object_id'), name='unique_user_like'),
        ),
    ]
