"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i$qxx!trdx411z=k=prgjabad87c+^rl)mk0g%gz71nsfv70v6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Required by django-allauth to tie users to a Site object
    "django.contrib.sites",
    # Third-party apps
    "django_seed",
    "widget_tweaks",
    # Local apps
    "market.apps.MarketConfig",
    # django-allauth apps
    # Core allauth functionality
    "allauth",
    # Email/password based authentication flows
    "allauth.account",
    # Core social account functionality
    "allauth.socialaccount",
    # Provider-specific apps for social login
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "allauth.socialaccount.providers.kakao",
    "allauth.socialaccount.providers.naver",
]

# Sites framework: required by django-allauth
# Make sure a Site with this ID exists in the database (see django.contrib.sites in the admin).
SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        # Still prevent passwords that are too similar to user attributes (e.g. email, username)
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        # Custom complexity rules: length, upper/lowercase letters, digits, special chars
        "NAME": "market.validators.CustomPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Europe/Berlin"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Instruct Django to use the custom User model defined in market/models.py
AUTH_USER_MODEL = "market.User"

# Tell Django which authentication backends to use.
# Keep the ModelBackend for Django admin and use the allauth backend for account/social logins.
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Redirect URLs used after login/logout (works for both account and social logins)

# URL name to redirect to after a successful login
# This resolves to the "home" view defined in market/urls.py
LOGIN_REDIRECT_URL = "home"

# URL name to redirect to after a successful logout
# Used by django-allauth when a user logs out
ACCOUNT_LOGOUT_REDIRECT_URL = "home"

# Explicitly tell django-allauth to use the same redirect target after login
# (defaults to LOGIN_REDIRECT_URL, but we set it here for clarity)
ACCOUNT_LOGIN_REDIRECT_URL = "home"

# Immediately log the user out on GET /accounts/logout/ without showing a confirmation page
ACCOUNT_LOGOUT_ON_GET = True

# Use email as the only login method (replacement for ACCOUNT_AUTHENTICATION_METHOD)
ACCOUNT_LOGIN_METHODS = {"email"}

# Define required signup fields
# (replacement for ACCOUNT_EMAIL_REQUIRED and ACCOUNT_USERNAME_REQUIRED)
# '*' marks the field as required.
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]

# Tell django-allauth to use a custom signup form instead of the default one
# The string value must be the full Python path to the custom form class
ACCOUNT_FORMS = {
    # Custom signup form that extends allauth's SignupForm
    # and adds support for the "nickname" field on the User model
    "signup": "market.forms.CustomSignupForm",
}

# Keep users logged in across browser sessions when "remember me" is used
ACCOUNT_SESSION_REMEMBER = True

# Keep the previously entered password value in the input field
# when the form is re-rendered (e.g., after validation errors).
# By default, password fields are cleared for security reasons.
ACCOUNT_PASSWORD_INPUT_RENDER_VALUE = True

# Require users to verify their email address before the account is fully active
ACCOUNT_EMAIL_VERIFICATION = "optional"

# Confirm the email as soon as the confirmation link is opened (GET request)
ACCOUNT_CONFIRM_EMAIL_ON_GET = True

# Automatically start the social login flow on GET (skip the intermediate confirmation page)
SOCIALACCOUNT_LOGIN_ON_GET = True

# Where to redirect an authenticated user after confirming their email
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = ("account_email_confirmation_done")

# Where to redirect an anonymous user after confirming their email
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = "account_email_confirmation_done"

# Remove the default subject prefix from all django-allauth emails
ACCOUNT_EMAIL_SUBJECT_PREFIX = ""

# Number of days a password reset link remains valid before it expires
PASSWORD_RESET_TIMEOUT_DAYS = 1

# Use the console email backend so all emails are printed to the terminal instead of being sent
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
