"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the .env file located in BASE_DIR.
# This makes keys such as SECRET_KEY, EMAIL_HOST_USER and EMAIL_HOST_PASSWORD
# available through os.environ.get(...) when Django starts.
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read SECRET_KEY from the environment instead of hard-coding it.
# If SECRET_KEY is not set, fail fast with a clear error so the project
# never runs with an empty or insecure secret key.
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY environment variable is not set.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

# Allowed hostnames for this Django site.
# Read from ALLOWED_HOSTS environment variable as a comma-separated list.
hosts = os.environ.get("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = hosts.split(",") if hosts else []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    # Required by django-allauth to tie users to a Site object
    "django.contrib.sites",
    # Third-party apps
    "django_seed",
    "widget_tweaks",
    # Local apps
    "market.apps.MarketConfig",
    # django-allauth apps
    # Core allauth functionality
    "allauth",
    # Email/password based authentication flows
    "allauth.account",
    # Core social account functionality
    "allauth.socialaccount",
    # Provider-specific apps for social login
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "allauth.socialaccount.providers.kakao",
    "allauth.socialaccount.providers.naver",
]

# Sites framework: required by django-allauth
# Make sure a Site with this ID exists in the database (see django.contrib.sites in the admin).
SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    
    # Redirect authenticated users with incomplete profiles to 'profile-set'.
    "market.middleware.ProfileRequiredMiddleware",
    
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
    # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        # Still prevent passwords that are too similar to user attributes (e.g. email, username)
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        # Custom complexity rules: length, upper/lowercase letters, digits, special chars
        "NAME": "market.validators.CustomPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Europe/Berlin"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Directory where 'collectstatic' will gather all static files for production.
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Instruct Django to use the custom User model defined in market/models.py
AUTH_USER_MODEL = "market.User"

# Tell Django which authentication backends to use.
# Keep the ModelBackend for Django admin and use the allauth backend for account/social logins.
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Redirect URLs used after login/logout (works for both account and social logins)

# URL name to redirect to after a successful login
# This resolves to the "home" view defined in market/urls.py
LOGIN_REDIRECT_URL = "home"

# URL name of the login view.
# Used by LoginRequiredMixin and Django's auth system when redirecting anonymous users.
LOGIN_URL = "account_login"

# URL name to redirect to after a successful logout
# Used by django-allauth when a user logs out
ACCOUNT_LOGOUT_REDIRECT_URL = "home"

# Explicitly tell django-allauth to use the same redirect target after login
# (defaults to LOGIN_REDIRECT_URL, but we set it here for clarity)
ACCOUNT_LOGIN_REDIRECT_URL = "home"

# Immediately log the user out on GET /accounts/logout/ without showing a confirmation page
ACCOUNT_LOGOUT_ON_GET = True

# Use email as the only login method (replacement for ACCOUNT_AUTHENTICATION_METHOD)
ACCOUNT_LOGIN_METHODS = {"email"}

# Define required signup fields
# (replacement for ACCOUNT_EMAIL_REQUIRED and ACCOUNT_USERNAME_REQUIRED)
# '*' marks the field as required.
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]

# Override default django-allauth forms with custom forms in the market app.
ACCOUNT_FORMS = {
    # Custom signup form (rendered on signup page).
    "signup": "market.forms.CustomSignupForm",
    # Custom login form (rendered on login page).
    "login": "market.forms.CustomLoginForm",
    # Custom password reset request form (password_reset.html).
    "reset_password": "market.forms.CustomResetPasswordForm",
    # Custom "set new password" form (password_reset_from_key.html).
    "reset_password_from_key": "market.forms.CustomResetPasswordFromKeyForm",
    # Custom password change form (password_change.html, when user is logged in).
    "change_password": "market.forms.CustomChangePasswordForm",
}

# Use a custom account adapter to control login/signup redirect behavior
ACCOUNT_ADAPTER = "market.adapters.CustomAccountAdapter"

# Keep users logged in across browser sessions when "remember me" is used
ACCOUNT_SESSION_REMEMBER = True

# Keep the previously entered password value in the input field
# when the form is re-rendered (e.g., after validation errors).
# By default, password fields are cleared for security reasons.
ACCOUNT_PASSWORD_INPUT_RENDER_VALUE = True

# Require users to verify their email address before the account is fully active
ACCOUNT_EMAIL_VERIFICATION = "optional"

# Confirm the email as soon as the confirmation link is opened (GET request)
ACCOUNT_CONFIRM_EMAIL_ON_GET = True

# Automatically start the social login flow on GET (skip the intermediate confirmation page)
SOCIALACCOUNT_LOGIN_ON_GET = True

# Where to redirect an authenticated user after confirming their email
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = ("account_email_confirmation_done")

# Where to redirect an anonymous user after confirming their email
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = "account_email_confirmation_done"

# Remove the default subject prefix from all django-allauth emails
ACCOUNT_EMAIL_SUBJECT_PREFIX = ""

# Number of days a password reset link remains valid before it expires
PASSWORD_RESET_TIMEOUT_DAYS = 1

# Configure Django to send email using Gmail's SMTP server.
# Sensitive values such as EMAIL_HOST_USER and EMAIL_HOST_PASSWORD
# must be provided via environment variables
# and should never be hard-coded in this settings module.
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Email account used to authenticate with the SMTP server.
# These values should be set via environment variables:
#   EMAIL_HOST_USER        - the Gmail address used to send emails
#   EMAIL_HOST_PASSWORD    - the app password associated with that account
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")

# Configure the logo used in HTML email templates.
# EMAIL_LOGO_PATH points to the logo file inside the static directory.
# EMAIL_LOGO_URL is the absolute URL used in templates as the <img src="..."> value.
# In development we fall back to a localhost URL, but in production this value
# should be provided via the EMAIL_LOGO_URL environment variable so that it
# uses the deployed site's domain.
EMAIL_LOGO_PATH = "market/assets/logo.png"
EMAIL_LOGO_URL = os.environ.get(
    "EMAIL_LOGO_URL",
    f"http://127.0.0.1:8000/{STATIC_URL}{EMAIL_LOGO_PATH}", 
)
